#!/bin/sh

source ~/.config/bspwm/bar/bar.cfg

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

xtitle -sf 'T%s' > "$PANEL_FIFO" &

# date & time
while true; do
   date +"c%A %x | %H:%M:%S"
   sleep 1
   done > "$PANEL_FIFO" &

# update checking
while true; do
   echo "u$(checkupdates | wc -l) updates"
   sleep 3600
   done > "$PANEL_FIFO" &

# get workspace info
groups() {
    cur=`xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}'`
    tot=`xprop -root _NET_NUMBER_OF_DESKTOPS | awk '{print $3}'`

    for w in `seq 0 $((cur - 1))`; do line="${line}*"; done
    line="${line}%{F#7FDD6E}*%{F-}"
    for w in `seq $((cur + 2)) $tot`; do line="${line}*"; done
    echo $line
}

# get volume info
volume() {
    VOLUME=$(amixer get Master | sed -n 'N;s/^.*\[\([0-9]\+%\).*$/\1/p')
    echo "$VOLUME"
}

# get cpu info
cpuload() {
    LINE=`ps -eo pcpu |grep -vE '^\s*(0.0|%CPU)' |sed -n '1h;$!H;$g;s/\n/ +/gp'`
    CPULOAD=$(bc <<< $LINE)
    echo "$CPULOAD"
}

# get memory info
memused() {
    read t f <<< `grep -E 'Mem(Total|Free)' /proc/meminfo | awk '{print $2}' | tr '\n' ' '`
    MEMORY=$(bc <<< "scale=2; 100 - $f / $t * 100" | cut -d. -f1)
    echo "$MEMORY"
}

# get battery info
Battery() {
    BATPERC=$(acpi --battery | cut -d, -f2)
    CHARGSTAT=$(acpi --battery | cut -d\  -f3 | awk '{ if($1 == "Discharging,") print "-"; else print "+";}')
    echo "$BATPERC $CHARGSTAT"
}

# print workspace info
while true; do
  echo "g$(groups)"
  sleep 0.5;
  done > "$PANEL_FIFO" &

# print volume info
while true; do
  echo "v$(volume)"
  sleep 10;
  done > "$PANEL_FIFO" &

# print cpu info
while true; do
  echo "l$(cpuload)"
  sleep 1;
  done > "$PANEL_FIFO" &

# print memory info
while true; do
  echo "m$(memused)"
  sleep 10;
  done > "$PANEL_FIFO" &

# print battery info
while true; do
  echo "b$(Battery)"
  sleep 1;
  done > "$PANEL_FIFO" &

while true; do
  interface=$WIFI_DEV
  ESSID=`iwconfig $interface | grep "ESSID:" | awk '{gsub(/[:"]/," "); print $5}'`
  echo "w$ESSID"
  sleep 300
  done > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ~/.config/bspwm/bar/panel_bar | lemonbar -g ${BARWIDTH}x${BARHEIGHT}+${EDGEWIDTH} -f "$PANEL_FONT_FAMILY" -F "$FOREGROUND" -B "$BACKGROUND" -u "$UNDERLINE_WIDTH" | while read line; do eval "$line"; done &

wait
