#!/bin/sh
source ~/.config/bspwm/bar/panel_colors

num_mon=$(bspc query -M | wc -l)
PADDING="  "

while read -r line ; do
	case $line in
		DAY*)
			# date output
			date="  %{B$COLOR_DTG_BG}%{F$COLOR_DTG_FG}  ${line#???}$PADDING%{F-}%{B-}"
			;;

    EMAIL*)
        # email alerts
        email="$PADDING${line#?????}$PADDING"
        ;;

    MESSAGE*)
        # Weechat messages
        messages="$PADDING${line#???????}$PADDING"
        ;;

    NEWS*)
        # Newsbeuter articles
        news="$PADDING${line#????}$PADDING"
        ;;

		MUSIC*)
			# music info
			music="$PADDING${line#?????}$PADDING"
			;;
		TIME*)
			# clock output
			clock="%{B$COLOR_DTG_BG}%{F$COLOR_DTG_FG}${line#????}$PADDING%{F-}%{B-}"
			;;

		BAT*)
			# battery percent output
			battery="$PADDING${line#???}$PADDING"
			;;
		SESSION_SUSPEND*)
			# suspend button output
			susp="%{F$COLOR_SESSION_FG}$PADDING${line#???????????????}$PADDING%{F-}"
			;;
		SESSION_POWER*)
			# power button output
			power="%{F$COLOR_SESSION_FG}$PADDING${line#?????????????}$PADDING%{F-}"
			;;

# uncomment for window title support
#		TITLE*)
#			# xtitle output
#			title="${line#?????}$PADDING$PADDING"
#			;;

		VOL*)
			# alsa volume
			volume="$PADDING${line#???}$PADDING"
			;;

		LINK*)
			# wifi link
			wifi="$PADDING${line#????}$PADDING"
			;;

		W*)
			# bspwm internal state
			wm_infos=""
      wsnr=1
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
						    desk="%{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
						    desk="%{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						desk="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}$PADDING${name}$PADDING%{B-}%{F-}"
            wm_infos="${wm_infos}%{A:bspc desktop -f "^$wsnr":}${desk}%{A}"
            wsnr=$((wsnr+1))
            ;;
					F*)
						# focused free desktop
						desk="%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}$PADDING${name}$PADDING%{B-}%{F-}"
            wm_infos="${wm_infos}%{A:bspc desktop -f "^$wsnr":}${desk}%{A}"
            wsnr=$((wsnr+1))
            ;;
					U*)
						# focused urgent desktop
						desk="%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}$PADDING${name}$PADDING%{B-}%{F-}"
            wm_infos="${wm_infos}%{A:bspc desktop -f "^$wsnr":}${desk}%{A}"
            wsnr=$((wsnr+1))
            ;;
					o*)
						# occupied desktop
            desk="%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}$PADDING${name}$PADDING%{B-}%{F-}"
            wm_infos="${wm_infos}%{A:bspc desktop -f "^$wsnr":}${desk}%{A}"
            wsnr=$((wsnr+1))
            ;;
					f*)
						# free desktop
						desk="%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}$PADDING${name}$PADDING%{B-}%{F-}"
            wm_infos="${wm_infos}%{A:bspc desktop -f "^$wsnr":}${desk}%{A}"
            wsnr=$((wsnr+1))
            ;;
					u*)
						# urgent desktop
						desk="%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}$PADDING${name}$PADDING%{B-}%{F-}"
            wm_infos="${wm_infos}%{A:bspc desktop -f "^$wsnr":}${desk}%{A}"
            wsnr=$((wsnr+1))
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm_infos}%{c}${music}%{r}${news}${messages}${email}${wifi}${volume}${battery}${date}${clock}${susp}${power}"
done
