#!/bin/sh

 FG='#839158'
 BG='#202529'
 conky -c ~/.config/dzen/scripts/.conkyrcdzen1 | dzen2 -e - -h '32' -w '1300' -ta l -x '300' -y 0 -fg $FG -bg $BG -fn 'Ubuntu:size=12' &

 conky -c ~/.config/dzen/scripts/.conkyrcdzen2 | dzen2 -e - -h '32' -w '960' -ta r -x '1600' -y 0 -fg $FG -bg $BG -fn 'Ubuntu:size=12' &
